module.exports = {
    // 회원가입
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    NOT_SAME_PASSWORD: 'NOT_SAME_PASSWORD',
    INVALID_FORMAT: 'INVALID_FORMAT',
    DUPLICATE_NICKNAME: 'DUPLICATE_NICKNAME',
    DUPLICATE_EMAIL: 'DUPLICATE_EMAIL',
    MISSING_FIELD: 'MISSING_FIELD',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    NULL_RESULT: 'NULL_RESULT',
};
